"""cache incident embedding and similarity

Revision ID: 6a16d014fb97
Revises: ee2ce44984b0
Create Date: 2026-09-27 17:39:30.605165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a16d014fb97'
down_revision: Union[str, Sequence[str], None] = 'ee2ce44984b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_analysis', sa.Column('runbook_similarity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_analysis', 'runbook_similarity')
    # ### end Alembic commands ###
