"""add incident embedding cache

Revision ID: ac351346b991
Revises: 6a16d014fb97
Create Date: 2026-09-27 17:41:24.455482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'ac351346b991'
down_revision: Union[str, Sequence[str], None] = '6a16d014fb97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('embedding', Vector(512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'embedding')
    # ### end Alembic commands ###
