"""add runbook embedding

Revision ID: ee2ce44984b0
Revises: ff76d2e52eaf
Create Date: 2026-09-27 17:11:02.178671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'ee2ce44984b0'
down_revision: Union[str, Sequence[str], None] = 'ff76d2e52eaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runbooks', sa.Column('embedding', Vector(512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runbooks', 'embedding')
    # ### end Alembic commands ###
