"""add runbook embedding

Revision ID: ff76d2e52eaf
Revises: a4607eaade46
Create Date: 2026-09-27 17:10:04.259579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff76d2e52eaf'
down_revision: Union[str, Sequence[str], None] = 'a4607eaade46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'ai_analysis', 'runbooks', ['runbook_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'ai_analysis', type_='foreignkey')
    # ### end Alembic commands ###
